business:
  info: Business Microserivce for Production from git.

spring:
    datasource:
    username: decompose-yelp
    password: yelp@12345
    url: jdbc:postgresql://localhost:5446/db-business
    driver-class-name: org.postgresql.Driver
jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
