server:
  port: 9090

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5169/oauth2
    username: oauth2
    password: oauth2
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: it.chhaya@gmail.com
    password: duuf wtgf nobv hggc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true